// Code generated by "stringer -type=ParseError -output=error_string.go"; DO NOT EDIT

package lzjson

import "fmt"

const _ParseError_name = "ErrorUndefinedErrorNotObjectErrorNotArray"

var _ParseError_index = [...]uint8{0, 14, 28, 41}

func (i ParseError) String() string {
	if i < 0 || i >= ParseError(len(_ParseError_index)-1) {
		return fmt.Sprintf("ParseError(%d)", i)
	}
	return _ParseError_name[_ParseError_index[i]:_ParseError_index[i+1]]
}
