// Code generated by "stringer -type=Type"; DO NOT EDIT

package lzjson

import "fmt"

const (
	_Type_name_0 = "TypeError"
	_Type_name_1 = "TypeUndefinedTypeStringTypeNumberTypeObjectTypeArrayTypeBoolTypeNull"
)

var (
	_Type_index_0 = [...]uint8{0, 9}
	_Type_index_1 = [...]uint8{0, 13, 23, 33, 43, 52, 60, 68}
)

func (i Type) String() string {
	switch {
	case i == -1:
		return _Type_name_0
	case 1 <= i && i <= 7:
		i -= 1
		return _Type_name_1[_Type_index_1[i]:_Type_index_1[i+1]]
	default:
		return fmt.Sprintf("Type(%d)", i)
	}
}
